### ISSUE TITLE
outback deploy panics with a nil pointer error when an ECS Service does not exist

### ISSUE THREAD

**Issue by walterbm** [koala-labs/outback#1]
When an ECS service that is listed in the outback config does not exist `outback deploy` will panic and throw a nil pointer error:

```
outback deploy -c dev 

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x160 pc=0x14e0282]

goroutine 1 [running]:
github.com/koala-labs/outback/pkg/outback.(*Outback).GetTaskDefinition(0xc0001ad000, 0xc000488ee0, 0x0)
	/Users/walter/go/pkg/mod/github.com/koala-labs/outback@v0.0.0-20211008200741-fd40e1b661f0/pkg/outback/outback.go:159 +0x42
github.com/koala-labs/outback/cmd/outback.deploy({0x7ffeefbffa72, 0xa}, 0x5)
	/Users/walter/go/pkg/mod/github.com/koala-labs/outback@v0.0.0-20211008200741-fd40e1b661f0/cmd/outback/deploy.go:78 +0x6a6
github.com/koala-labs/outback/cmd/outback.runDeploy(0x1c70ce0, {0x16ea4ce, 0x2, 0x2})
	/Users/walter/go/pkg/mod/github.com/koala-labs/outback@v0.0.0-20211008200741-fd40e1b661f0/cmd/outback/deploy.go:25 +0x2e
github.com/spf13/cobra.(*Command).execute(0x1c70ce0, {0xc0001c5260, 0x2, 0x2})
	/Users/walter/go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:762 +0x60e
github.com/spf13/cobra.(*Command).ExecuteC(0x1c711a0)
	/Users/walter/go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:852 +0x2dc
github.com/spf13/cobra.(*Command).Execute(...)
	/Users/walter/go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:800
github.com/koala-labs/outback/cmd/outback.Execute()
	/Users/walter/go/pkg/mod/github.com/koala-labs/outback@v0.0.0-20211008200741-fd40e1b661f0/cmd/outback/root.go:38 +0x25
main.main()
	/Users/walter/go/pkg/mod/github.com/koala-labs/outback@v0.0.0-20211008200741-fd40e1b661f0/main.go:6 +0x17
```

Most likely the error result from `outback.GetService` is not working as expected:

https://github.com/koala-labs/outback/blob/ccba2eaed9ec1c90d11a5ceb5504ef95d05b9e5b/cmd/outback/deploy.go#L68-L72

**Comment by walterbm** [comment]
Resolved by this commit: https://github.com/koala-labs/outback/commit/ccba2eaed9ec1c90d11a5ceb5504ef95d05b9e5b
